version: '3'
services:
  frontend:
    build: ./frontend
    # image: khoirobert/blask_frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    # volumes:
    #   - ./frontend:/home/BLASK_FE/:ro
  api:
    build: ./BLASK_server
    # image: khoirobert/blask
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    volumes:
       - media:/mediafiles/
    # volumes:
    #   - ./BLASK_server/:/home/BLASK/:ro
    # command: python manage.py runserver 0.0.0.0:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Son[1122002]
      - DATABASE_NAME=BLASK_DB
      - SECRET_KEY=Son[1122002]Anh[4102002]
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Son[1122002]
      - POSTGRES_DB=BLASK_DB
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:5

volumes:
  postgres-db:
  media: