# Generated by Django 4.1.2 on 2022-11-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.AddField(
            model_name='question',
            name='numOfSecond',
            field=models.IntegerField(default=10),
        ),
    ]
