# Generated by Django 4.1.2 on 2022-11-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_rename_userof_quiz_userof"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="UserOf",
            new_name="userOf",
        ),
    ]
