# Generated by Django 4.1.2 on 2022-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_time_question_numofsecond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='defautTitle', max_length=100),
        ),
    ]
