# Generated by Django 4.1.2 on 2022-11-14 12:33

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.upload_to),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.upload_to),
        ),
    ]
